### PR TITLE
Create submission API

### PR DESCRIPTION
**Pull request by cjchirag7**
For #60 
Changes in brief
- MySQL Tables modified to separate MCQ and Subjective Submissions
- Create Submission API made supporting MCQ submission as well as subjective submissions
- A minor fix in `/contests/:contest_id/participate` API to allow to participate only when a contest is active or upcoming

### CODE REVIEW

**Comment by cjchirag7** [comment]
**In practise section, let us keep only coding questions.** There's no meaning of keeping MCQ and subjective questions over there. As it wouldn't be possible to judge the responses of subjective question of a person who submitted long after the contest for **practice**?
Thoughts, @ridhishjain @NBNARADHYA

**Review by NBNARADHYA — CHANGES_REQUESTED** [review]
LGTM!

**Review by NBNARADHYA — APPROVED** [review]
LGTM!

**Review by ridhishjain — APPROVED** [review]
Looks good

**Pull request merged**
